DROP TABLE USERS;
/*DROP TABLE USERS_GROUPS;*/
DROP TABLE USERS_SUBSCRIBES;

----------------------- CREATIION TABLE ------------------------------
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CREATION_TIMESTAMP NOT NULL,
    IDENTIFIER INTEGER NOT NULL,
    FULL_NAME TEXT,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    /*USER_GROUP_ID INTEGER NOT NULL,*/
    IS_ACTIVE BOOLEAN NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    /*IS_BANNED  BOOLEAN NOT NULL CHECK (IS_BANNED IN (0,1)),*/
    CHANGE_TIMESTAMP INTEGER NOT NULL
    /*FOREIGN KEY (USER_GROUP_ID) REFERENCES USERS_GROUPS (ID)*/
);


/*CREATE TABLE USERS_GROUPS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME_GROUP TEXT
);*/

CREATE TABLE USERS_SUBSCRIBES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    SUBSCRIBING TEXT,
    CHANGE_TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);